version: "3.8"
services:
  app:
    container_name: "sb_container"
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_db:5432/springdb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=171819
    depends_on:
      - postgres_db

  postgres_db:
    container_name: "postgres_db"
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=171819
      - POSTGRES_DB=springdb

volumes:
    postgres_data: